### ISSUE TITLE
Your PHP installation is older than version 5.3.7

### ISSUE THREAD

**Issue by terracenter** [zanhsieh/docker-ocs-inventory-ng#1]
HI.
Your PHP installation is older than version 5.3.7 and will not be compatible with incoming versions ( version : 5.3.3 )

**Comment by zanhsieh** [comment]
add webtatic repo as quick fix after experiment a lot of options:
1. upgrade to centos 7
- required the host daemon have systemd too.
- no mariadb s6 on centos 7
- switch to ubuntu / debian based lamp stack
- configs of lamp on different location
  if anybody would like to have #1 and could tolerate host system needed to be centos 7, i'll post that repo online
